### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Olegatro** [Igor10k/ikSelect#41]
Привет, некоторые соображения по поддержке:
* package.json
* bower.json
* jshint
* ci (travis-ci ?) 
* testing
* отделить исходники от продакшена(в последнее время часто вижу структуру, dist и src, но тут, наверное, каждый сам решает)

С тестами не работал, но было бы интересно попробовать, если решите завести.

Могу потихоньку добавлять.

**Comment by igor10k** [comment]
Спустя пол года я добрался-таки.
Добавил `package.json`, `bower.json`, `.jshintrc`, разделил структуру на `src` и `dist`.
Тесты это конечно было бы круто, но сомневаюсь, что я до них доберусь в ближайшем будущем. Впрочем, если кто-то сделает PR с тестами, то с радостью его смерджу.
