### ISSUE TITLE
Изменение окна браузера

### ISSUE THREAD

**Issue by Makvagabo** [Igor10k/ikSelect#43]
Если selec открыт и изменить, например, ширину окна браузера, то selec оказывается не на своём месте.
Можно либо скрывать, либо с помощью debounce повесить событие resize и переопределять положение.

**Comment by Igor10k** [comment]
Я об этом знаю, не вижу смысла добавлять что-то для этого крайне редкого юзкейса. В тех случаях когда это необходимо, можно без проблем прицепиться к ресайзу самому и делать с дропдаунами что угодно )
Сейчас подумал, что наверное стоит добавить `onInit` колбэк, чтоб проще получать инстэнс. Потому что сейчас для этого придется писать че-то типа `$(selector).ikSelect().data('plugin_ikSelect')`. Не красиво.
