### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by olegatro** [Igor10k/ikSelect#48]
Привет, думаю стоит добавить библиотеку в какой нибудь cdn ресурс для библиотек? 
Например, cdnjs или jsdelivr

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/
